# Generated by Django 3.1.2 on 2020-10-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='system_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.TextField()),
                ('logs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='system_Utilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.TextField()),
                ('ram_usage', models.TextField()),
                ('cpu_usage', models.TextField()),
                ('disk_usage', models.TextField()),
                ('time_stamp', models.TextField()),
            ],
        ),
    ]
