# Generated by Django 3.1.3 on 2020-11-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_system_utilities_time_stamp_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_Utilities_Desktops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.TextField()),
                ('ram_usage', models.TextField()),
                ('cpu_usage', models.TextField()),
                ('disk_usage', models.TextField()),
                ('time_stamp', models.TextField()),
                ('time_stamp_format', models.TextField(default='SOME STRING', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='system_Utilities_Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.TextField()),
                ('ram_usage', models.TextField()),
                ('cpu_usage', models.TextField()),
                ('disk_usage', models.TextField()),
                ('time_stamp', models.TextField()),
                ('time_stamp_format', models.TextField(default='SOME STRING', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='system_Utilities_Tablets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.TextField()),
                ('ram_usage', models.TextField()),
                ('cpu_usage', models.TextField()),
                ('disk_usage', models.TextField()),
                ('time_stamp', models.TextField()),
                ('time_stamp_format', models.TextField(default='SOME STRING', max_length=140)),
            ],
        ),
        migrations.RenameModel(
            old_name='system_Utilities',
            new_name='system_Utilities_Laptops',
        ),
        migrations.DeleteModel(
            name='system_logs',
        ),
    ]
