# Generated by Django 3.1.3 on 2021-01-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20201116_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_utilities_desktops',
            name='remote_application',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='system_utilities_desktops',
            name='remote_id',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='system_utilities_laptops',
            name='remote_application',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='system_utilities_laptops',
            name='remote_id',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='system_utilities_servers',
            name='remote_application',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='system_utilities_servers',
            name='remote_id',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
