# Generated by Django 3.1.3 on 2021-02-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210213_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_utilities_desktops',
            name='anydesk_id',
            field=models.TextField(default='Not Applied'),
        ),
        migrations.AlterField(
            model_name='system_utilities_desktops',
            name='teamviewer_id',
            field=models.TextField(default='Not Applied'),
        ),
        migrations.AlterField(
            model_name='system_utilities_laptops',
            name='anydesk_id',
            field=models.TextField(default='Not Applied'),
        ),
        migrations.AlterField(
            model_name='system_utilities_laptops',
            name='teamviewer_id',
            field=models.TextField(default='Not Applied'),
        ),
        migrations.AlterField(
            model_name='system_utilities_servers',
            name='anydesk_id',
            field=models.TextField(default='Not Applied'),
        ),
        migrations.AlterField(
            model_name='system_utilities_servers',
            name='teamviewer_id',
            field=models.TextField(default='Not Applied'),
        ),
    ]
