# Generated by Django 3.1.3 on 2021-02-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20210213_0643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='system_Utilities_Laptops',
            new_name='system_Utilities_Systems',
        ),
        migrations.DeleteModel(
            name='system_Utilities_Desktops',
        ),
    ]
