# Generated by Django 3.1.3 on 2021-02-23 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20210216_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_utilities_servers',
            name='server_type',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
